global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-lumi-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["backend:8080"]
        labels:
          application: "api-coragpt"